### ISSUE TITLE
Sometimes Breaking-News Content won't load!

### ISSUE THREAD

**Issue by staxDB** [humhub-contrib/breakingnews#10]
Hey there, 
I recognized a strange problem with this module.....

If a user is already on the dashboard, when someone creates new breaking news content, and then clicks the dashboard link again, a window opens, but sometimes no content is loaded....

I have attached a gif to demonstrate the issue:

![issue-breakingnews](https://user-images.githubusercontent.com/8705799/37254473-9eced600-253e-11e8-970c-518a62516d70.gif)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub-contrib/breakingnews/pull/14.

**Comment by luke-** [comment]
@yurabakhtin thanks, please see my remarks.
