### ISSUE TITLE
Suggestion: Send breaking news to selected users.

### ISSUE THREAD

**Issue by catalinchertes** [humhub-contrib/breakingnews#20]
It would be nice if there was an option to send the message only to a group of people besides seding to everyone.

**Comment by funkycram** [comment]
I also need this feature.
@luke- if you agree, I can sen a PR for this feature.

In the module settings, I can add a checkbox list of all groups with:
- label: "Groups whose members will see this breaking news"
- Hint: "If no group is ticked, everyone will see this breaking news"

**Comment by luke-** [comment]
@funkycram Sounds good. Feel free to add this feature!

**Comment by funkycram** [comment]
@luke- https://github.com/humhub-contrib/breakingnews/pull/26
I added screenshots in https://github.com/humhub-contrib/breakingnews/pull/26 to show the new settings page.
I added the groups checkbox list in a collapsible block in case there a to many groups.

**Comment by luke-** [comment]
@funkycram Thanks!
