### ISSUE TITLE
Suggestion/ FR: Display news beyond the Dashboard

### ISSUE THREAD

**Issue by dantefromhell** [humhub-contrib/breakingnews#23]
As the Breaking News module is built to only trigger on the Dashboard, users of platforms that have the `homeUrl` config option [1] set will miss the news until they manually navigate to the Dashboard.

It would be great if the Breaking News module displays the announcement beyond the dashboard. I can think of multiple options, but I'm not sure what a sensible default would be:
1) Every page (CON: could disrupt users workflows)
2) Automatically enable on the page configured via `homeUrl` (CON: Might be tricky to document)
3) Have an option to explicitly select pages that trigger the module

[1] https://github.com/humhub/humhub/pull/3568

**Comment by luke-** [comment]
https://github.com/humhub-contrib/breakingnews/pull/25
