### ISSUE TITLE
Rename "Expired at" to "Expire"

### ISSUE THREAD

**Issue by marc-farre** [humhub-contrib/breakingnews#37]
An English speaker's suggestion:

Current:
![image](https://github.com/user-attachments/assets/e756f4bc-4117-42c6-a81e-ad2719db7fa4)

Suggestion:
![image](https://github.com/user-attachments/assets/0a04ac3f-d92f-46e5-a2c6-0c5de0ae2c96)

**Comment by marc-farre** [comment]
@luke- if you agree, I'll send a PR

**Comment by luke-** [comment]
@Semir1212 Can you confirm?

**Comment by Semir1212** [comment]
Yes @marc-farre @luke-

**Comment by marc-farre** [comment]
@luke- @Semir1212 Thanks!
PR https://github.com/humhub-contrib/breakingnews/pull/38
